const tvlTypeOpts = {
  PACKG: "package",
  ETK: "flight",
  TRANSF: "transfers",
  HOTEL: "hotel",
  EXCH: "exchange",
  CRUISE: "cruise",
  SVCFEE: "service fee",
  CAR: "car",
  DTECHG: "date change",
  INS: "insurance",
  REBATE: "rebate",
  ACT: "activity",
  CNLFEE: "xnl fee",
  FEE: "fee",
  CHN: "change",
  TOUR: "tour",
  ADJMNT: "adjustment",
  CREDIT: "travel credit",
  RAIL: "rail",
  MISC: "misc",
};

const supplierOpts = {
  PICASSO: "PIC",
  EXPEDIA: "EXP",
  KAYAK: "KYK",
  ORBITZ4AGENTS: "ORB",
  ALLABOUT: "ALL",
  UNITEDTOURS: "UAT",
  USVACS: "USV",
  VACSEX: "VEX",
  PLEASANT: "PLS",
  AAGROUP: "AAG",
  PRINCESS: "PRC",
  RUSHAWAII: "RHW",
  JETBLUE: "JTB",
  DELTA: "DAL",
  AIRFARE: "AFR",
  ORBITZ: "ORB",
  VAYAMA: "VAY",
  HAL: "HAL",
  JUSTFLY: "JST",
  BEDS: "BED",
  TPI: "TPI",
  GOGO: "GOG",
};

const vendorOpts = {
  RCCL: "RCL",
  HOLLAND: "HAL",
  HAL: "HAL",
  NCL: "NCL",
  NORWEG: "NCL",
  CARNIVAL: "CRN",
  CARNIVL: "CRN",
  CARNVL: "CRN",
  CARNL: "CRN",
  CUNARD: "CUN",
  PRINCESS: "PRN",
  PRINCES: "PRN",
  CELEBR: "CBR",
  FUNJET: "FUN",
  ORBITZ: "ORB",
  BEDSONL: "BED",
  PLEASANT: "PLS",
  EXPEDIA: "EXP",
  VACEXPRESS: "VEX",
  VACXPRES: "VEX",
  VACSEX: "VEX",
  VACEX: "VEX",
  VACSSEX: "VEX",
  TGUARD: "TVG",
  TVLGRD: "TVG",
  ALLIANZ: "ALZ",
  AEROMEX: "AMX",
  AEROVACS: "AMX",
  ASVACS: "ASV",
  AAVACS: "AAV",
  PRICELN: "PRL",
  GOTORUS: "GTR",
  DLVACS: "DLV",
  DELTAVACS: "DLV",
  ALLABOUT: "ALL",
  USVACS: "USV",
  GOGOVACS: "GOG",
  ACCESS: "ACC",
  VAX: "VAX",
  MLTVACS: "MLT",
  JETSET: "JET",
  BLUESKY: "BLU",
  UNITED: "UAV",
  UAVACS: "UAV",
  APPLE: "APL",
  PICASSO: "PIC",
  WNVACS: "WNV",
  TBD: "TBD",
  IB: "IBA",
  QR: "QRA",
  NZ: "NZA",
  FI: "FIA",
  MU: "MUA",
  QF: "QFA",
  OZ: "OZA",
  ET: "ETA",
  SL: "SLA",
  AB: "ABA",
  RJ: "RJA",
  AY: "AYA",
  EY: "EYA",
  S7: "S7A",
  UT: "UTA",
  JJ: "JJA",
  SN: "SNA",
  R3: "R3A",
  CA: "CAA",
  VA: "VAA",
  CZ: "CZA",
  AZ: "AZA",
  VS: "VSA",
  AA: "AAA",
  SK: "SKA",
  AF: "AFA",
  EK: "EKA",
  SA: "SAA",
  KL: "KLM",
  US: "USA",
  PS: "PSA",
  BT: "BTA",
  SU: "SUA",
  DL: "DLA",
  UA: "UAL",
  DE: "DEA",
  LH: "LHA",
  LO: "LOT",
  UN: "UNA",
  B6: "B6A",
  KE: "KEA",
  AS: "ASA",
  TK: "TKA",
  HY: "HYA",
  LY: "LYA",
  VV: "VVA",
  OS: "OSA",
  "9U": "9UA",
  BA: "BAA",
  LX: "LXA",
  AC: "ACA",
  TA: "TAA",
  HU: "HUA",
  PR: "PRA",
  SQ: "SQA",
  WN: "WNA",
  J2: "J2A",
};

export function getSupplierOpts() {
  return supplierOpts;
}

export function getTvlTypeOpts() {
  return tvlTypeOpts;
}

export function getVendorOpts() {
  return vendorOpts;
}
